Feature/co 815 gender inclusive rr implementation
osu-mist/locations-api pull request #30
Opened 2017-06-12 21:45 UTC by jaredkosanovic

2017-06-19 19:24 UTC, floppyears requested changes

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/db/ArcGisDAO.groovy
> +            }
How about if we add an else statement and log as a warning or error the if the centroid data building is not found?

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/db/ArcGisDAO.groovy
> +    private def getArcGisData(String url, String output, String key) throws Exception{
Let's add a comment to this helper method

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/db/ArcGisDAO.groovy
> +        genderInclusiveRRData.each {id, value ->
Let's move the merging logic into a separate small method. This will allow you to easily write a unit test for the merging logic. Otherwise you'd have to mock the getArcGisData method which requires more work.

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/db/LocationDAO.groovy
> +                arcGisCentroids[bldNamIdHash].coordinatesType = it['geometry']['type']
If the building is not in arcGisCentroids, is that considered an error? If yes, let's add an else statement with a log error or warning output.

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/mapper/LocationMapper.groovy
> +            type: Constants.TYPE_BUILDING,
Would a campusmap location have giRestroom data? Wouldn't the arcgis be the only datasource that comes with giRestroom data?

2017-06-19 19:24 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/mapper/LocationMapper.groovy
> +        } else if (restroomLimitString && restroomLimitString.trim().length() == 0 ) {
If you use a couple of groovy shortcuts this method could be simplified to something like:
if (restroom == null) {
return null
} 

restroomLimitString?.trim()

In groovy, empty or null strings evaluate to false: http://docs.smartthings.com/en/latest/getting-started/groovy-basics.html#groovy-truth . Let's also add a unit test for this method

2017-06-19 19:49 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/core/ArcGisLocation.groovy
> +        giRestroomCount ?: 0
In this method, let's also do a validation and check that the count provided is equal to the number of entries in giRestroomLocations . For example, when doing a visual check, I found that Resr provides a count of 5, but 13 are mentioned in the restroom locations

2017-06-20 17:06 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/locations/db/LocationDAO.groovy
> +                arcGisCentroids[bldNamIdHash].coordinatesType = it['geometry']['type']
Not considered an error, but it's worth logging.

2017-06-20 17:36 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/locations/mapper/LocationMapper.groovy
> +            type: Constants.TYPE_BUILDING,
ArcGis is merged into a campus map location object in this method: https://github.com/osu-mist/locations-api/blob/feature/CO-815-gender-inclusive-rr-implementation/src/main/groovy/edu/oregonstate/mist/locations/db/LocationDAO.groovy#L97-L123

2017-06-20 18:44 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/locations/core/ArcGisLocation.groovy
> +        giRestroomCount ?: 0
As we discussed, we'll have an integration test do this validation

2017-06-20 21:54 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/locations/mapper/LocationMapper.groovy
> +            type: Constants.TYPE_BUILDING,
Yep, you're right.

2017-06-20 21:59 UTC, floppyears approved these changes

2017-06-21 19:52 UTC, merged