CO-935: update skeleton
osu-mist/locations-api pull request #39
Opened 2017-09-29 17:28 UTC by magical

2017-09-29 17:33 UTC, jaredkosanovic approved these changes
Looks good

2017-09-29 17:35 UTC, jaredkosanovic requested changes
Actually, could you update the configuration-example to give the endpointUri?

2017-09-29 17:36 UTC, magical commented
sure, good catch

2017-09-29 17:41 UTC, magical commented
done

2017-10-09 22:14 UTC, jaredkosanovic approved these changes

2017-10-12 21:11 UTC, merged