Implement GET /locations/{locationId}/services
osu-mist/locations-api pull request #82
Opened 2020-08-20 22:24 UTC by kalcicd

2020-08-20 23:10 UTC, Ruefa requested changes

2020-08-20 23:10 UTC, Ruefa commented on src/db/awsEs/compound-request-dao.js
> +  _.forEach(rawLocation.relationships.services.data, (value) => serviceIds.push(value.id));
Looks like you are just trying to get a list of `id`. Using `_.map()` would be better https://lodash.com/docs/4.17.15#map

2020-08-20 23:10 UTC, Ruefa commented on src/db/awsEs/compound-request-dao.js
> +const buildBulkIdQueryBody = (ids, type) => {
JSDoc for these two functions

2020-08-25 18:41 UTC, Ruefa approved these changes

2020-08-25 18:42 UTC, Ruefa requested changes
Looks like there are merge conflicts now

2020-08-25 18:56 UTC, kalcicd commented
fixed.

2020-08-25 20:03 UTC, tsoliangwu0130 approved these changes

2020-08-25 20:04 UTC, merged